#### **NUMPY**

## Bài 3.1 – Phiên bản NumPy và cấu hình build

In [1]:
import numpy as np
print("NumPy version:", np.__version__)
print("\nNumPy build config:")
np.show_config()

NumPy version: 2.3.5

NumPy build config:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.1",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35219",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tire4up4/cp313-win_amd64/build/venv/Lib/site-packages/sci

c:\Users\admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


## Bài 3.2 – Thao tác array cơ bản

In [2]:
import numpy as np

arr = np.arange(10)
print("arr:", arr)
print("dtype:", arr.dtype, "shape:", arr.shape)

arr_odd = arr[arr % 2 == 1]
arr_even = arr[arr % 2 == 0]
print("arr_odd:", arr_odd)
print("arr_even:", arr_even)

arr_update_1 = arr.copy()
arr_update_1[arr_update_1 % 2 == 1] = 100
print("arr_update_1:", arr_update_1)

arr: [0 1 2 3 4 5 6 7 8 9]
dtype: int64 shape: (10,)
arr_odd: [1 3 5 7 9]
arr_even: [0 2 4 6 8]
arr_update_1: [  0 100   2 100   4 100   6 100   8 100]


## Bài 3.3 – Lọc phần tử xuất hiện ở arr_a

In [3]:
import numpy as np
arr_a = np.array([1,2,3,2,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

arr_c = arr_b[np.isin(arr_b, arr_a)]
print("arr_c:", arr_c)

arr_c: [2 2 4 4]


## Bài 3.4 – Thao tác mảng nâng cao

In [4]:
import numpy as np

# 1
arr_zero = np.zeros(10, dtype=int)
arr_zero[5] = 1
print("arr_zero:", arr_zero)

# 2
arr_h = np.arange(10, 21)
print("arr_h reversed:", arr_h[::-1])

# 3
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
print("arr_k non-zero:", arr_k[arr_k != 0])

# 4
arr_add = np.arange(5)
arr_add = np.append(arr_add, [10, 20])
print("arr_add:", arr_add)

# 5
arr_ins = np.arange(10)
arr_ins = np.insert(arr_ins, 5, 100)
print("arr_ins:", arr_ins)

# 6
arr_del = np.delete(arr_ins, [0,1,2])
print("arr_del:", arr_del)

arr_zero: [0 0 0 0 0 1 0 0 0 0]
arr_h reversed: [20 19 18 17 16 15 14 13 12 11 10]
arr_k non-zero: [1 2 8 2 1 3 5]
arr_add: [ 0  1  2  3  4 10 20]
arr_ins: [  0   1   2   3   4 100   5   6   7   8   9]
arr_del: [  3   4 100   5   6   7   8   9]


## Bài 3.5 – MLB Heights & Weights (giả lập)

In [5]:
import numpy as np

# Giả lập dữ liệu nhỏ
heights = np.array([180, 175, 190, 185])  # cm
weights = np.array([75, 70, 90, 85])      # kg

height_m = heights / 100
bmi = weights / (height_m ** 2)

print("BMI:", bmi)
print("BMI < 21:", bmi[bmi < 21])
print("Avg height:", heights.mean(), "Avg weight:", weights.mean())
print("Max height:", heights.max(), "Max weight:", weights.max())
print("Min height:", heights.min(), "Min weight:", weights.min())

BMI: [23.14814815 22.85714286 24.93074792 24.83564646]
BMI < 21: []
Avg height: 182.5 Avg weight: 80.0
Max height: 190 Max weight: 90
Min height: 175 Min weight: 70


## Bài 3.6 – Ma trận 2D

In [6]:
import numpy as np

arr = np.full((3,3), True)
print(arr)

arr1 = np.arange(1, 9).reshape(4,2)
print(arr1[:, ::-1])

print(arr1[::-1, :])
print(arr1[:, ::-1])

arr_nan = np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9]])
print("Has NaN:", np.isnan(arr_nan).any())
arr_nan[np.isnan(arr_nan)] = 0
print(arr_nan)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[2 1]
 [4 3]
 [6 5]
 [8 7]]
[[7 8]
 [5 6]
 [3 4]
 [1 2]]
[[2 1]
 [4 3]
 [6 5]
 [8 7]]
Has NaN: True
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]]


## Bài 3.7 – Baseball (giả lập)

In [7]:
import numpy as np

np_baseball = np.array([[180,75],[175,70],[190,90]])
print("dtype:", np_baseball.dtype, "shape:", np_baseball.shape)

print("Height mean:", np_baseball[:,0].mean())
print("Weight mean:", np_baseball[:,1].mean())

dtype: int64 shape: (3, 2)
Height mean: 181.66666666666666
Weight mean: 78.33333333333333


## Bài 3.8 – Trung bình chiều cao theo vị trí (giả lập)

In [8]:
import numpy as np

positions = np.array(['GK','DF','MF','FW','DF'])
heights = np.array([190,180,175,178,182])

for pos in np.unique(positions):
    print(pos, heights[positions == pos].mean())

DF 181.0
FW 178.0
GK 190.0
MF 175.0


## Bài 3.9 – Euro 2012 

In [9]:
import pandas as pd

data = {
    "Team": ["A","B","C"],
    "Goals": [5,3,4],
    "Yellow Cards": [2,4,1],
    "Red Cards": [0,1,0]
}
euro12 = pd.DataFrame(data)
print(euro12)
print("Avg Yellow:", euro12["Yellow Cards"].mean())

  Team  Goals  Yellow Cards  Red Cards
0    A      5             2          0
1    B      3             4          1
2    C      4             1          0
Avg Yellow: 2.3333333333333335


## Bài 3.10 – Drinks 

In [10]:
import pandas as pd

drinks = pd.DataFrame({
    "country":["A","B","C"],
    "beer_servings":[100,200,150]
})
print(drinks.describe())

       beer_servings
count            3.0
mean           150.0
std             50.0
min            100.0
25%            125.0
50%            150.0
75%            175.0
max            200.0


## Bài 3.11 – Stocks 

In [11]:
import pandas as pd

stocks = pd.DataFrame({
    "open":[10,12,11],
    "close":[12,11,13]
})
stocks["result"] = stocks["close"] - stocks["open"]
print(stocks)

   open  close  result
0    10     12       2
1    12     11      -1
2    11     13       2


## Bài 3.12 – Movies 

In [12]:
import pandas as pd

movies = pd.DataFrame({
    "title":["M1","M2"],
    "year":[2020,2021],
    "rating":[7.5,8.0]
})
print(movies)

  title  year  rating
0    M1  2020     7.5
1    M2  2021     8.0
